version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: fhedb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr"]
      interval: 5s
      timeout: 5s
      retries: 5

  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-only-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  server:
    image: ghcr.io/jessepinkman9900/fhe-db-search/server:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - vault
    environment:
      RUST_LOG: info
      APP_DATABASE_URL: postgres://usr:pwd@postgres:5432/fhedb
      APP_VAULT_ADDR: http://vault:8200
      APP_VAULT_TOKEN: dev-only-token
    healthcheck:
      test: ["CMD", "server", "health"]
      interval: 5s
      timeout: 5s
      retries: 5

  client:
    image: ghcr.io/jessepinkman9900/fhe-db-search/client:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - vault
    environment:
      RUST_LOG: info
      APP_DATABASE_URL: postgres://usr:pwd@postgres:5432/fhedb
      APP_VAULT_ADDR: http://vault:8200
      APP_VAULT_TOKEN: dev-only-token
    healthcheck:
      test: ["CMD", "client", "health"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    
