[toolchain]
channel = "nightly"
version = "1.85.1"
components = [
    "cargo",
    # "clippy",
    "rust-analyzer",
    # "rust-src",
    "rust-std",
    "rustc",
    # "rustfmt",
]
# targets = ["wasm32-unknown-unknown"]
