[package]
name = "database"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true

[dependencies]
diesel = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
